from tkinter import *
root = Tk()
a = Entry(root)
a.grid(row=0, column=0, columnspan=3)
c = Button(root, text="1")
c.grid(row=1, column=0)
d = Button(root, text="2")
d.grid(row=1, column=1)
e = Button(root, text="3")
e.grid(row=1, column=2)
f = Button(root, text="4")
f.grid(row=2, column=0)
g = Button(root, text="5")
g.grid(row=2, column=1)
h = Button(root, text="6")
h.grid(row=2, column=2)
i = Button(root, text="7")
i.grid(row=3, column=0)
j = Button(root, text="8")
j.grid(row=3, column=1)
k = Button(root, text="9")
k.grid(row=3, column=2)
l = Button(root, text="+")
l.grid(row=4, column=0)
m = Button(root, text="-")
m.grid(row=4, column=1)
n = Button(root, text="x")
n.grid(row=4, column=2)
o = Button(root, text="/")
o.grid(row=5, column=0)
p = Button(root, text="=")
p.grid(row=5, column=1)
q = Button(root, text="clear")
q.grid(row=5, column=2)
root.mainloop()